use std::{fs, path::PathBuf, process::Command};

use chems_conformance::validate_repository;
use serde_json::{Value, json};

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}

#[test]
fn repository_contract_is_internally_valid() {
    let summary =
        validate_repository(&workspace_root()).expect("repository contract should validate");
    assert_eq!(summary.grammar_productions, 42);
    assert_eq!(summary.components, 13);
    assert_eq!(summary.cases, 19);
    assert_eq!(summary.incomplete_cases, 6);
    assert!(!summary.is_complete());
}

#[test]
fn language_contract_fixture_is_executable_and_bound_to_normative_authority() {
    let root = workspace_root();
    let contract: Value = serde_json::from_str(
        &fs::read_to_string(
            root.join("conformance/specification/language-contract-001.input.json"),
        )
        .expect("language contract should be readable"),
    )
    .expect("language contract should be JSON");
    assert_eq!(
        contract,
        json!({
            "schema_version": 1,
            "language": "chems 1",
            "authority": "authored source plus host-trusted catalogue and mandatory kernel",
            "supported_output": "representative structural outcome with explanatory sequence",
            "non_goals": [
                "laboratory procedure",
                "bulk material model",
                "molecular dynamics",
                "universal reaction prediction",
                "mechanism proof"
            ],
            "conformance_authority": [
                "docs/chems-specification.md",
                "grammar/chems.ebnf",
                "conformance/requirements.json",
                "conformance/manifest.json"
            ]
        })
    );

    for authority in contract["conformance_authority"].as_array().unwrap() {
        let path = authority.as_str().unwrap();
        assert!(root.join(path).is_file(), "missing authority: {path}");
    }
    let specification = fs::read_to_string(root.join("docs/chems-specification.md")).unwrap();
    for heading in [
        "## Language charter",
        "## Authority boundaries",
        "## Non-goals",
        "## Conformance contract",
    ] {
        assert!(
            specification.contains(heading),
            "missing section: {heading}"
        );
    }
    assert!(specification.contains("representative`"));
    assert!(specification.contains("`sequence := explanatory`"));
    assert!(specification.contains("must not be\ngenerated by the implementation under test"));

    let requirements: Value = serde_json::from_str(
        &fs::read_to_string(root.join("conformance/requirements.json")).unwrap(),
    )
    .unwrap();
    let specification_requirements = requirements["requirements"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|requirement| requirement["component"] == "specification")
        .map(|requirement| requirement["id"].as_str().unwrap())
        .collect::<std::collections::BTreeSet<_>>();
    assert_eq!(
        specification_requirements,
        ["CHR-001", "CHR-002", "CHR-003", "CNF-001"]
            .into_iter()
            .collect()
    );

    let manifest: Value =
        serde_json::from_str(&fs::read_to_string(root.join("conformance/manifest.json")).unwrap())
            .unwrap();
    let case = manifest["cases"]
        .as_array()
        .unwrap()
        .iter()
        .find(|case| case["id"] == "language-contract-001")
        .expect("language contract case should be registered");
    assert_eq!(case["component"], "specification");
    assert_eq!(case["expected"]["state"], "validated");
    assert_eq!(
        case["requirements"],
        json!(["CHR-001", "CHR-002", "CHR-003", "CNF-001"])
    );
}

#[test]
fn canonical_expansion_oracle_has_total_immutable_state_chain() {
    let root = workspace_root();
    let oracle: Value = serde_json::from_str(
        &fs::read_to_string(root.join("conformance/expansion/canonical-expansion-001.hir.json"))
            .expect("expansion oracle should be readable"),
    )
    .expect("expansion oracle should be JSON");
    let states = oracle["states"]
        .as_array()
        .expect("oracle should contain states");
    let operations = oracle["operations"]
        .as_array()
        .expect("oracle should contain operations");
    let expected_atoms = oracle["atom_elements"]
        .as_object()
        .expect("oracle should define stable atom identities")
        .keys()
        .cloned()
        .collect::<std::collections::BTreeSet<_>>();

    assert_eq!(states.len(), 13);
    assert_eq!(operations.len(), 12);
    assert_eq!(expected_atoms.len(), 8);

    for (index, state) in states.iter().enumerate() {
        assert_eq!(state["id"], format!("state[{index}]"));
        let actual_atoms = state["atoms"]
            .as_object()
            .expect("every state should contain every atom")
            .keys()
            .cloned()
            .collect::<std::collections::BTreeSet<_>>();
        assert_eq!(actual_atoms, expected_atoms);
        assert!(state["covalent_edges"].is_array());
        assert!(state["metallic_domains"].is_array());
        assert!(state["ionic_associations"].is_array());
        assert!(state["product_assignments"].is_array());
        let ledger = &state["ledger"];
        let atom_local_non_bonding = state["atoms"]
            .as_object()
            .expect("atoms should be an object")
            .values()
            .map(|atom| atom[1].as_i64().expect("electron count should be integral"))
            .sum::<i64>();
        let atom_formal_charge_sum = state["atoms"]
            .as_object()
            .expect("atoms should be an object")
            .values()
            .map(|atom| atom[0].as_i64().expect("formal charge should be integral"))
            .sum::<i64>();
        let covalent_bond_electrons = state["covalent_edges"]
            .as_array()
            .expect("edges should be an array")
            .iter()
            .map(|edge| match edge[2].as_str() {
                Some("single") => 2,
                Some("double") => 4,
                Some("triple") => 6,
                order => panic!("unsupported oracle bond order: {order:?}"),
            })
            .sum::<i64>();
        let metallic_domain_electrons = state["metallic_domains"]
            .as_array()
            .expect("domains should be an array")
            .iter()
            .map(|domain| domain[2].as_i64().expect("domain count should be integral"))
            .sum::<i64>();
        assert_eq!(ledger["atom_local_non_bonding"], atom_local_non_bonding);
        assert_eq!(ledger["atom_formal_charge_sum"], atom_formal_charge_sum);
        assert_eq!(ledger["covalent_bond_electrons"], covalent_bond_electrons);
        assert_eq!(
            ledger["metallic_domain_electrons"],
            metallic_domain_electrons
        );
        assert_eq!(
            atom_local_non_bonding + covalent_bond_electrons + metallic_domain_electrons,
            18
        );
        assert_eq!(ledger["total_explicit_valence_electrons"], 18);
        assert_eq!(ledger["system_net_charge"], 0);
        assert_eq!(
            ledger["system_net_charge"].as_i64(),
            Some(
                ledger["atom_formal_charge_sum"]
                    .as_i64()
                    .expect("formal-charge sum should be integral")
                    - ledger["metallic_domain_electrons"]
                        .as_i64()
                        .expect("domain-electron count should be integral")
            )
        );
    }

    for (index, operation) in operations.iter().enumerate() {
        assert_eq!(operation["id"], format!("operation[{}]", index + 1));
        assert_eq!(operation["before_state"], format!("state[{index}]"));
        assert_eq!(operation["after_state"], format!("state[{}]", index + 1));
    }
}

#[test]
fn canonical_rule_fixture_is_executable_data_not_prose() {
    let root = workspace_root();
    let catalogue: Value = serde_json::from_str(
        &fs::read_to_string(root.join("conformance/catalogue/lithium-rule-001.catalogue.json"))
            .expect("catalogue fixture should be readable"),
    )
    .expect("catalogue fixture should be JSON");
    let bundle = &catalogue["bundle"];
    let rule = &bundle["rules"][0];

    let resolved_premises = bundle["premises"]
        .as_array()
        .expect("premises should be an array")
        .iter()
        .filter_map(|record| record["id"].as_str())
        .collect::<std::collections::BTreeSet<_>>();

    assert_eq!(rule["reactant_pattern"].as_array().map(Vec::len), Some(2));
    assert_eq!(rule["product_pattern"].as_array().map(Vec::len), Some(2));
    assert_eq!(rule["mapping_template"].as_array().map(Vec::len), Some(8));
    assert_eq!(
        rule["operation_template"].as_array().map(Vec::len),
        Some(12)
    );
    assert_eq!(
        rule["observation_compatibility"].as_array().map(Vec::len),
        Some(2)
    );
    assert!(rule["applicability"]["premise_id"].is_string());
    let rule_premises = rule["premise_ids"]
        .as_array()
        .expect("rule premise IDs should be an array");
    assert!(!rule_premises.is_empty());
    for premise in rule_premises {
        assert!(
            resolved_premises.contains(
                premise
                    .as_str()
                    .expect("rule premise ID should be a string")
            ),
            "unresolved rule premise: {premise}"
        );
    }
}

#[test]
fn partial_suite_reports_incomplete_coverage() {
    let output = Command::new(env!("CARGO_BIN_EXE_chems-conformance"))
        .arg("report")
        .output()
        .expect("conformance runner should start");
    assert_eq!(output.status.code(), Some(3));
    assert!(!String::from_utf8_lossy(&output.stdout).contains("cases   0"));
    assert!(
        String::from_utf8_lossy(&output.stdout)
            .contains("frames               cases   1; requirements   1/1")
    );
    assert!(
        String::from_utf8_lossy(&output.stderr).contains("conformance is incomplete"),
        "incomplete result was not explicit: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(
        String::from_utf8_lossy(&output.stdout).contains("6 incomplete"),
        "incomplete case count was missing: {}",
        String::from_utf8_lossy(&output.stdout)
    );
}

#[test]
fn manifest_schema_checks_case_evidence_and_identifier_shape() {
    let root = workspace_root();
    let schema: Value = serde_json::from_str(
        &fs::read_to_string(root.join("conformance/manifest.schema.json"))
            .expect("manifest schema should be readable"),
    )
    .expect("manifest schema should be JSON");
    let validator = jsonschema::draft202012::new(&schema).expect("manifest schema should compile");
    let mut manifest: Value = serde_json::from_str(
        &fs::read_to_string(root.join("conformance/manifest.json"))
            .expect("manifest should be readable"),
    )
    .expect("manifest should be JSON");
    manifest["cases"] = json!([{
        "id": "tab-indentation-001",
        "component": "parsing",
        "requirements": ["LEX-009"],
        "source": "conformance/parsing/tab-indentation-001.chems",
        "expected": {
            "state": "malformed",
            "diagnostics": [{
                "code": "CHEMS-L001",
                "severity": "Error",
                "primary_span": {
                    "fixture": "conformance/parsing/tab-indentation-001.chems",
                    "start": 0,
                    "end": 1
                }
            }],
            "formatted_source": "conformance/parsing/tab-indentation-001.formatted.chems"
        }
    }]);
    assert!(validator.is_valid(&manifest));

    let mut string_diagnostic = manifest.clone();
    string_diagnostic["cases"][0]["expected"]["diagnostics"] = json!(["CHEMS-L001"]);
    assert!(!validator.is_valid(&string_diagnostic));

    let mut repeated_hyphen = manifest;
    repeated_hyphen["components"][0]["id"] = json!("bad--component");
    assert!(!validator.is_valid(&repeated_hyphen));
}
